### PR TITLE
Include all swagger-ui resources on GraalVM

### PR DESCRIPTION
**Pull request by FieryCod**

### CODE REVIEW

**Comment by Deraen** [comment]
This should be fine.

Can you point me to some GraalVM documentation for this argument and what does it do?

**Comment by FieryCod** [comment]
Swagger-ui resources are not included into native-image. With the `IncludeResources` the resources are merged with the binary and accessible via a special "resource:" protocol. See https://github.com/ring-clojure/ring/pull/447 for more context. 

https://www.graalvm.org/reference-manual/native-image/Resources/

**Comment by Deraen** [comment]
https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/

> A recommended way to provide configuration is to embed a native-image.properties file into a project JAR file.

I'm trying to understand what is the practice with libraries regarding this configuration. That page mentions "a project JAR," but I'm not sure if it means "a project" as in the consumer app or includes libraries.

But based on discussion from a Graal issue (https://github.com/oracle/graal/issues/2535) and libraries like ojdbc and okhttp (https://github.com/square/okhttp/tree/master/okhttp/src/main/resources/META-INF/native-image/okhttp/okhttp), it does indeed seem to be normal for libs to include configuration for themselves.

**Comment by FieryCod** [comment]
The libraries in general should ship their own `native-image.properties`. However not all the libraries are interested in having the support for GraalVM. The other case is that some libraries offer limited set of native-configuration, to prevent the extra build size (more reflection-config.json entries = bigger binary size). 

Anyway for above mentioned cases we have https://github.com/clj-easy/graal-config.

**Comment by Deraen** [comment]
This change is now deployed in versions 3.52.3 and 3.46.0-1.

**Pull request merged**
